### ISSUE TITLE
First try at using this

### ISSUE THREAD

**Issue by vanfanel** [OpenGM8/GM8Decompiler#10]
Hi,

First of all, thanks for this tool! I can appreciate the work put into this.
I am trying to use it for the first time (no instructions on the README), so after building the project with

`cargo build`

I tried to decompile a GM project with these results:

```
manuel@hp15db0:~/Downloads/maldita$ gm8decompiler maldita_castilla_arcade_cabinet.exe 
GM8Decompiler v2.0.6 for x86_64-unknown-linux-gnu - built on 2020/12/11, #16c5534
Input file: maldita_castilla_arcade_cabinet.exe
WARNING: Failed to recover an icon: id 1, rva 0x55B9A8
Error parsing gamedata:
Reader error: io error: failed to fill whole buffer

manuel@hp15db0:~/Downloads/maldita$ file data.win 
data.win: IFF data

```

Maybe data.win should have another name? Is this compatible with Windows executables only?

**Comment by notviri** [comment]
Games with "data.win" files are made with GameMaker:Studio, not GM8. This tool is not for decompiling studio games. GM8 only supported the Windows target with bundled data (further elaborated on in the README), therefore the input must be an EXE.

For unpacking GM:S games, try out this project: https://gitlab.com/PoroCYon/Altar.NET

**Comment by notviri** [comment]
Alright then.

**Comment by vanfanel** [comment]
@notviri Thanks for your response! I have just seen it, sorry.
