### ISSUE TITLE
Can it be packaged and released? It's been a long time since the update was released.

### ISSUE THREAD

**Issue by s-svip** [OpenGM8/GM8Decompiler#14]
Can it be packaged and released? It's been a long time since the update was released.

**Comment by notviri** [comment]
I'm glad you asked, currently touching up for the v2.1 bump! So, very soon, yes.

**Comment by s-svip** [comment]
Thank you, thank you for your contribution.

**Comment by s-svip** [comment]
I have a GM8 I Wanna that cannot be decompiled. Can I send an email to you?

**Comment by notviri** [comment]
It'd be much easier if you joined the Discord listed in the README. If you don't want to, email viriviwi@gmail.com

**Comment by Adamcake** [comment]
Hello, this game was made with Clickteam Fusion, not GM8. You'd need a Clickteam Fusion decompiler to decompile this game. Or you could just ask MattinJ for the source code - his contacts are listed in the game's readme.
