### ISSUE TITLE
click and drag it on top of the executable？

### ISSUE THREAD

**Issue by maxyip** [OpenGM8/GM8Decompiler#20]
Drag and drop did not respond in the past, what kind of operating environment does the application need?

**Comment by Adamcake** [comment]
Dragging a game EXE onto the decompiler EXE in most file explorers is the same as running the decompiler with the game as the first argument. In other words, it should produce a GMK. If it doesn't, the game probably isn't made with GameMaker 8.

If you'd like us to check if the decompiler is working correctly then can you send us a download link for the game you're trying to decompile?

**Comment by maxyip** [comment]
this link
-----------

https://w3g3a5v6.ssl.hwcdn.net/upload2/game/767928/4180967?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1670430182&Signature=tDhhtzymJbs3Bu4k46bQy6VuGGod0Z8o063WbnqRDMF4fVDqz159jpim%2B8hfJdJ2%2FB6KvoUERgv%2F4JieCSUZA9%2FgS9NRUHGpTSPe1xFmhThX%2B64bV%2FYdN%2FZvboiNsUih%2BOsIuFztiVavsZZDiK6xGiLZiO9n%2Bqy8ftcpneHUu93o64AuB2LS6sPDXzodFbrTwHY9b198T0riCAUHMEmeIvjsytW2zs7T1tjXgGytqF491qjZ1iqoqmbuGwpXflY%2BkSQLA0WqJrUBu%2FC0BEXTF2Gig%2B0wbMZ8xbOMZRyVK742ThRWlAyqGOidXuLP6nzRTdRU7GP2zD5d3M9x9mmH%2BA==&hwexp=1670430442&hwsig=f562b6f8ef7bbd65aed9a76a911e216d

**Comment by Adamcake** [comment]
That's a GameMaker Studio game, so not Gamemaker 8 which is why our decompiler can't do anything with it. For Studio games you can look at using something like [UndertaleModTool](https://github.com/krzys-h/UndertaleModTool) or [Altar.NET](https://github.com/PoroCYon/Altar.NET), but these generally need more effort to decompile.
