### ISSUE TITLE
Reader error: invalid exe header

### ISSUE THREAD

**Issue by 666DHG** [OpenGM8/GM8Decompiler#29]
`GM8Decompiler v2.2.0 for i686-pc-windows-msvc - built on 2024/2/12, #fb6d4d57
Input file: B:\SteamLibrary\steamapps\common\vividstasis\VIVIDSTASIS.exe
Verbose logging ON: verbose console output enabled
Error parsing gamedata:
Reader error: invalid exe header`
I wonder what it means.

**Comment by Adamcake** [comment]
Either the file is not a valid exe file at all, or it's not an x86 exe.

The most likely cause is that it's a 64-bit exe (x86_64), in which case it
can't possibly have been made with gamemaker 8.

**Comment by BenjaminUrquhart** [comment]
vivid/stasis is a gamemaker studio game, you can use UndertaleModTool to open it (the latest release at the time of writing won’t work, you need to use a bleeding edge version).

**Comment by 666DHG** [comment]
> vivid/stasis is a gamemaker studio game, you can use UndertaleModTool to open it (the latest release at the time of writing won’t work, you need to use a bleeding edge version).

Thanks! That helps a lot!
